@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeletePatientParser" as DeletePatientParser LOGIC_COLOR
participant "d:DeletePatientCommand" as DeletePatientCommand LOGIC_COLOR
end box

[-> LogicManager : execute("...")
note right
  ... indicates delete t/patient P001
end note
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("...")
activate AddressBookParser

create DeletePatientParser
AddressBookParser -> DeletePatientParser
activate DeletePatientParser

DeletePatientParser --> AddressBookParser
deactivate DeletePatientParser

AddressBookParser -> DeletePatientParser : parse("P001")
activate DeletePatientParser

create DeletePatientCommand
DeletePatientParser -> DeletePatientCommand
activate DeletePatientCommand

DeletePatientCommand --> DeletePatientParser : d
deactivate DeletePatientCommand

DeletePatientParser --> AddressBookParser : d
deactivate DeletePatientParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeletePatientParser -[hidden]-> AddressBookParser
destroy DeletePatientParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

ref over LogicManager, DeletePatientCommand : Delete Patient Command Execution

@enduml
