@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam ClassAttributeFontColor #FFFFFF
skinparam classAttributeIconSize 0

package Model <<Rectangle>> {
Abstract Class Id

Class Doctor {
    -department: Department
    -phone: Phone
    -name: Name
}

Class Patient {
    -height: Height
    -weight: Weight
    -age: Age
    -gender: Gender
    -bloodType: BloodType
}

Class Activity {
    -description: Description
    -title: Title
    -startTime: Time
    -endTime: Time
}

Class UserProfile

Class Name
Class Phone
Class Tag

Class ActivityId
Class Description
Class Title
Class Time

Class Department
Class DoctorId

Class Age
Class BloodType
Class Gender
Class Height
Class PatientId
Class Weight

Class Organization
Class Department
Class Position
}
show Activity members
show Doctor members
show Patient members
show UserProfile members

PatientId --|> Id
DoctorId --|> Id
ActivityId -right-|> Id

Patient *-up-> Age
Patient *-up-> BloodType
Patient *-up-> Gender
Patient *--> Height
Patient *--> Weight
Patient *--> PatientId
Patient *--> Phone
Patient *--> Name
Patient *-right-> "*" Tag

Doctor *--> Name
Doctor *--> Phone
Doctor *--> DoctorId
Doctor *--> Department

Activity *--> ActivityId
Activity - Patient

UserProfile *-up-> Name
UserProfile *--> Organization
UserProfile *--> Position
UserProfile *--> Department

@enduml
