@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam ClassAttributeFontColor #FFFFFF
skinparam classAttributeIconSize 0

Package Model <<Rectangle>>{

class "{abstract}\nPerson" as Person {
    -name: Name
    -phone: Phone
    -id: Id
}

Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>

Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class UniquePersonList
Class UniqueActivityList
Class ObservableUserProfile

Class Activity {
    -description: Description
    -title: Title
    -startTime: Time
    -endTime: Time
    -activityId: ActivityId
}
Class Patient {
    -height: Height
    -weight: Weight
    -age: Age
    -gender: Gender
    -bloodType: BloodType
}
Class Doctor {
    -department: Department
}
Class UserProfile {
    -organization: Organization
    -position: Position
    -department: Department
}

}

show Patient members
show Person members
show Activity members
show Doctor members
show UserProfile members

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -right-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *-left-> "1" UniqueActivityList
AddressBook *-down-> "1" ObservableUserProfile
AddressBook *--> "2" UniquePersonList

ObservableUserProfile --> "1" UserProfile

UniquePersonList --> "*" Patient
UniquePersonList --> "*" Doctor

Patient -left-|> Person
Doctor --|> Person

Patient - Activity

ModelManager -->"*" Patient
ModelManager -->"*" Doctor
ModelManager -left->"*" Activity

UniqueActivityList -right-> "*" Activity
@enduml
