@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Abstract Class Person

Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>

Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniquePersonList
Class UniqueActivityList
Class ObservableUserProfile
Class Activity
Class Patient
Class Doctor
Class UserProfile
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -right-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *-left-> "1" UniqueActivityList
AddressBook *-left-> "1" ObservableUserProfile
AddressBook *--> "1" UniquePersonList

ObservableUserProfile --> "1" UserProfile

UniquePersonList --> "~* all" Patient
UniquePersonList --> "~* all" Doctor

Patient -up-|> Person
Doctor --|> Person

ModelManager -->"~* filtered" Patient
ModelManager -->"~* filtered" Doctor
ModelManager -left->"~* filtered" Activity

UniqueActivityList -right-> "~* all" Activity
@enduml
